jaffle_shop:
  target: bv
  outputs:
    bv:
      type: bv_duckdb
      host: localhost
      port: 5433
      delegate: dev
      api_port: 3000
      database: main
      schema: analytics
      threads: 4
    dev:
      type: duckdb
      path: 'jaffle_shop.duckdb'
